project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "files/"
    - "projects/"


# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/Excel2R.bib
csl: files/bib/chicago-author-date.csl
description-meta: "Use modern statistical and data scientific tools to measure causal effects and evaluate public policy"

website:
  title: "Compendio sull'analisi dei dati in Excel e R"
  site-url: "https://lulliter.github.io/CompendioExcel2R"
  # "https://evalsp23.classes.andrewheiss.com"

  favicon: "/files/xls_icons8.png"

  twitter-card:
    image: "/files/foto_stock_analisi.png"
    card-style: summary_large_image
    creator: "@lulliter"
    # site: "@andrewheiss"

  open-graph:
    image: "/files/foto_stock_analisi.png"
    locale: en_US

  navbar:
    pinned: true
    background: "#EE6A24"
    right:
      - index.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Examples"
        file: example/index.qmd
      - text: "Resources"
        file: resource/index.qmd

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Course content"
          contents:
            - text: "1: Evaluation and the causal revolution"
              file: content/01-content.qmd
            - text: "2: Regression and inference"
              file: content/02-content.qmd
    - title: "Examples"
      contents:
        - section: "Overview"
          contents:
            - example/index.qmd
        - section: "Examples"
          contents:
            - example/dags.qmd
    - title: "Resources"
      contents:
        - section: "Overview"
          contents:
            - resource/index.qmd
            - resource/data.qmd
            - resource/citations.qmd


# {{variable }} in YAML https://stackoverflow.com/questions/41620674/use-placeholders-in-yaml
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
